# Generated by Django 3.2.20 on 2023-07-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
    ]
